controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_controller:
      type: position_controllers/JointGroupPositionController

arm_controller:
  ros__parameters:
    joints:
      - joint1_shoulder_yaw
      - joint2_shoulder_pitch
      - joint3_elbow_pitch
      - joint4_wrist_pitch
      - joint5_wrist_yaw
      - joint6_wrist_roll
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    open_loop_control: false
    allow_integration_in_goal_trajectories: true

gripper_controller:
  ros__parameters:
    joints:
      - gripper_left_finger_joint
      - gripper_right_finger_joint
    interface_name: position
